# Generated by Django 3.1.7 on 2021-08-31 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('institute', models.CharField(max_length=128)),
                ('experience', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('linkedin', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc', models.DateField(null=True)),
                ('hsc', models.DateField(null=True)),
                ('honours', models.DateField(null=True)),
                ('master', models.DateField(null=True)),
                ('extra', models.CharField(blank=True, max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='crudapi.teacherdetail')),
            ],
        ),
    ]
