# Generated by Django 3.1.7 on 2021-08-25 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('institute', models.CharField(max_length=128)),
                ('experience', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('linkedin', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
