# Generated by Django 2.2.12 on 2021-09-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='crudapi.TeacherDetail'),
        ),
    ]
